export const qk = {
  character: ['character'] as const,
  profile: ['profile'] as const,
  modules: ['modules'] as const,
  skills: ['skills'] as const,
  habits: ['habits'] as const,
  difficulties: ['difficulties'] as const,
  todayLogs: (date: string) => ['habitLogs', date] as const,
  periodLogs: (date: string) => ['periodLogs', date] as const,
  habitLogsRoot: ['habitLogsByHabit'] as const,
  habitLogs: (habitId: string) => ['habitLogsByHabit', habitId] as const,
  monthLogs: (month: string) => ['monthLogs', month] as const,
  summary: ['dailySummary'] as const,
  systemItems: ['systemItems'] as const,
  rewards: ['rewards'] as const,
  activeBuffs: ['activeBuffs'] as const,
  inventory: ['inventory'] as const,
  inventoryTransactions: ['inventoryTransactions'] as const,
  userItems: ['userItems'] as const,
  purchases: ['purchases'] as const,
  achievements: ['achievements'] as const,
  sideQuests: ['sideQuests'] as const,
  inactiveHabits: ['inactiveHabits'] as const,
  bodyParts: ['bodyParts'] as const,
  fitnessExercises: ['fitnessExercises'] as const,
  workoutSessions: ['workoutSessions'] as const,
  completedSessions: ['completedSessions'] as const,
  workoutSession: (id: string) => ['workoutSession', id] as const,
  workoutTemplates: ['workoutTemplates'] as const,
  workoutTemplatesAll: ['workoutTemplatesAll'] as const,
  workoutTemplateRoot: ['workoutTemplate'] as const,
  workoutTemplate: (id: string) => ['workoutTemplate', id] as const,
  workoutRecords: ['workoutRecords'] as const,
  workoutSets: (sessionId: string) => ['workoutSets', sessionId] as const,
  exerciseSets: (exerciseId: string) => ['exerciseSets', exerciseId] as const,
  bodyMeasurements: ['bodyMeasurements'] as const,
  bodyGoals: ['bodyGoals'] as const,
  bodyAlertSettings: ['bodyAlertSettings'] as const,
  attributes: ['attributes'] as const,
  equipmentCatalog: ['equipmentCatalog'] as const,
  myEquipment: ['myEquipment'] as const,
  currentSeason: ['currentSeason'] as const,
  seasonStory: ['seasonStory'] as const,
  seasonSaga: ['seasonSaga'] as const,
  objectivesOverview: ['objectivesOverview'] as const,
  objectiveSuggestions: ['objectiveSuggestions'] as const,
  notificationSnapshot: ['notificationSnapshot'] as const,
};
